- id: arXiv:2306.17638
  link: https://dl.acm.org/doi/10.5555/3618408.3619483
  publisher: ICML
  category: recent

- id: arXiv:2305.13316
  link: https://doi.org/gs93pm
  publisher: JCP
  category: recent

- id: arXiv:2210.07702
  link: https://proceedings.neurips.cc/paper_files/paper/2022/hash/0206c1c20a18915da23df5e61966fc6a-Abstract-Conference.html
  publisher: NeurIPS
  category: recent

- id: arXiv:2206.01816
  publisher: ICLR 
  category: recent
 
- id: url:https://proceedings.mlr.press/v162/sanmarti-n22a.html
  title: The Algebraic Path Problem for Graph Metrics
  link: https://proceedings.mlr.press/v162/sanmarti-n22a.html
  authors:
    - "Enrique Fita Sanmart\xEDn"
    - Sebastian Damrich
    - Fred A. Hamprecht
  date: '2022-07-17'
  publisher: ICML
  category: recent

- id: arXiv:2103.14608
  link: https://proceedings.neurips.cc/paper/2021/hash/2de5d16682c3c35007e4e92982f1a2ba-Abstract.html
  publisher: NeurIPS
  category: recent

